name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  imageRegistry: dockerHubRegistryServiceConnection

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: $(imageRegistry)
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    repository: fongshway/pipenv
- task: Docker@2
  displayName: Logout of Docker Hub
  inputs:
    command: logout
    containerRegistry: $(imageRegistry)
