version: "3"
services:

  pytest:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: pytest -v --junitxml=/app/test_report.xml
