version: "3"
services:

  pytest:
    container_name: pytest
    hostname: pytest
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:rw
