name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  imageRegistry: dockerHubRegistryServiceConnection

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: Setup
  jobs:
  - job: SetupJob
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(imageRegistry)
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        repository: fongshway/pipenv
- stage: Teardown
  jobs:
  - job: TeardownJob
    steps:
    - task: Docker@2
      displayName: Logout of Docker Hub
      inputs:
        command: logout
        containerRegistry: $(imageRegistry)
